# Generated by Django 6.0.5 on 2026-05-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
