# Generated by Django 6.0.5 on 2026-05-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_contactmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('discount_type', models.CharField(choices=[('percent', 'Процентная скидка'), ('fixed', 'Фиксированная скидка (в рублях)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Для процентов – число от 0 до 100, для фиксированной – сумма в рублях', max_digits=10)),
                ('apply_to', models.CharField(choices=[('all', 'На все товары'), ('category', 'На категорию'), ('product', 'На конкретный товар')], default='all', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория (если применимо)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Товар (если применимо)')),
            ],
            options={
                'verbose_name': 'Акция/скидка',
                'verbose_name_plural': 'Акции/скидки',
                'ordering': ['-start_date'],
            },
        ),
    ]
