# Generated by Django 6.0.5 on 2026-05-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date']},
        ),
    ]
