# Generated by Django 6.0.5 on 2026-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_promotion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='app.category', verbose_name='Категории (если выбран тип "На категории")'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='app.product', verbose_name='Товары (если выбран тип "На товары")'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='apply_to',
            field=models.CharField(choices=[('all', 'На все товары'), ('categories', 'На выбранные категории'), ('products', 'На выбранные товары')], default='all', max_length=10),
        ),
    ]
